name: Pull Request actions
on:
  - pull_request
jobs:

  label:
    name: 'PR Labeler'
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fmt:
    name: 'Terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: examples
          tf_actions_version: '0.12.17'
          tf_actions_subcommand: 'fmt'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: 'Build example docs'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout at ref
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout
      if: github.event.pull_request.head.repo.full_name != github.repository
      uses: actions/checkout@v2

    - name: Should generate USAGE.md for tf11_basic
      uses: ./
      with:
        tf_docs_working_dir: examples/tf11_basic
        tf_docs_template: |
          # Test tf11 basic

          # Usage
          <!--- BEGIN_TF_DOCS --->
          <!--- END_TF_DOCS --->

    - name: Should generate USAGE.md for tf11_extra_args
      uses: ./
      with:
        tf_docs_working_dir: examples/tf11_extra_args
        tf_docs_content_type: document
        tf_docs_indention: '3'
        tf_docs_args: '--no-required'
        tf_docs_output_method: replace

    - name: Should inject into README.md
      uses: ./
      with:
        tf_docs_working_dir: examples/tf12_basic
        tf_docs_output_file: README.md
        tf_docs_args: ''

    - name: Should generate README.md for tf12_atlantis
      uses: ./
      with:
        tf_docs_atlantis_file: atlantis.yaml
        tf_docs_output_file: README.md

    - name: Should generate README.md for tf12_find and its submodules
      uses: ./
      with:
        tf_docs_find_dir: examples/tf12_find

    - name: Should generate README.md for tf12_inject and push up all changes
      uses: ./
      with:
        tf_docs_find_dir: examples/tf12_inject
        tf_docs_output_file: README.md

    - name: Push up changes
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: ./
      with:
        tf_docs_working_dir: examples/tf12_basic
        tf_docs_content_type: json
        tf_docs_output_method: print
        tf_docs_git_push: 'true'
        tf_docs_git_commit_message: 'chore: terraform-docs build'
